#!/usr/bin/env python
# coding: utf-8

# # Assignment 1

# ## Test your knowledge. 
# 
# ** Answer the following questions **

# ## Strings

# Given the string 'hello' give an index command that returns 'e'. Enter your code in the cell below:

# In[1]:


s = 'hello'
# Print out 'e' using indexing
print([s[1]])


# Reverse the string 'hello' using slicing:

# In[27]:


s ='hello'
# Reverse the string using slicing
#for i in range(len(s)-1,-1,-1):
 #   print(s[i])
print(s[-1:-6:-1])


# Given the string hello, give two methods of producing the letter 'o' using indexing.

# In[29]:


s ='hello'
# Print out the 'o'

# Method 1:

s[4]


# In[31]:


# Method 2:
s[len(s)-1]


# ## Lists

# Build this list [0,0,0] two separate ways.

# In[37]:


# Method 1:
x=list([0,0,0])
x


# In[38]:


# Method 2:
x=[0,0,0]
x


# Reassign 'hello' in this nested list to say 'goodbye' instead:

# In[43]:


list3 = [1,2,[3,4,'hello']]

list3[2][2]="goodbye"
list3


# Sort the list below:

# In[49]:


list4 = [5,3,4,6,1]
list4=set(list4)
list4=list(list4)
list4


# ## Dictionaries

# Using keys and indexing, grab the 'hello' from the following dictionaries:

# In[51]:


d = {'simple_key':'hello'}
# Grab 'hello'
d.get("simple_key")


# In[62]:


d = {'k1':{'k2':'hello'}}
# Grab 'hello'
d.get("k1").get('k2')
#y.get("k2")


# In[68]:


d = {'k1':[{'nest_key':['this is deep',['hello']]}]}

#Grab hello
y=d.get("k1")
k=y[0].get('nest_key')
k[1][0]


# In[82]:


d = {'k1':[1,2,{'k2':['this is tricky',{'tough':[1,2,['hello']]}]}]}
#Grab hello
y=d.get('k1')
z=y[2].get('k2')
d=z[1].get('tough')
d[2][0]


# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# ** Given the variables:**
# 
#     planet = "Earth"
#     diameter = 12742
# 
# ** Use .format() to print the following string: **
# 
#     The diameter of Earth is 12742 kilometers.

# In[1]:


planet='Earth'
diameter=12742
print('the diameter of {} is {} kilometers'.format(planet,diameter))


# ** Given this nested list, use indexing to grab the word "hello" **

# In[6]:


lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
lst[3][1][2][0]


# In[ ]:





# ** Given this nested dictionary grab the word "hello". **

# In[12]:


d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d.get('k1')[3].get('tricky')[3].get('target')[3]


# In[ ]:





# ### Write a Python program to swap two variables.
# 

# In[26]:


_1st=int(input('enter 1st variable'))
_2nd=int(input('enter 2nd variable'))
def swap(x,y):
    z=x
    x=y
    y=z
    print('1st variable = {}'.format(x))
    print('2nd variable = {}'.format(y))
    
swap(_1st,_2nd)


# ## Thanks

# In[ ]:




