#!/usr/bin/env python
# coding: utf-8

# # Assignment 3

# ### Write a function to count the number 4 in a given list.

# In[62]:


def qwe(s):
    y=0
    for i in range(0,len(s)):
        if s[i]==4:
            y+=1 
    return y
d=[1,2,5,3,4,6,4,7,8,4,5,2,4]
qwe(d)


# ### write a  function to check whether a number is divisible by another number.

# In[6]:


y=int(input("enter a number: "))
def div(x):
    if(x%2==0):
        print("the number is divisable by 2\n")
    if (x%3==0):
       print("the number is divisable by 3\n")
    if (x%4==0):
        print("the number is divisable by 4\n")
    if (x%5==0):
        print("the number is divisable by 5\n")
    if(x%6==0):
        print("the number is divisable by 6\n")
    if(x%7==0):
        print("the number is divisable by 7\n")
    if(x%8==0):
        print("the number is divisable by 8\n")
    if(x%9==0):
        print("the number is divisable by 9\n")
div(y)


# ### write a function to find the maximum and minimum numbers from a sequence of numbers.

# In[21]:


def maxmin(x):
    maxx=x[0]
    minn=x[0]
    for i in range(0,len(x)):
        if x[i]>maxx:
            maxx=x[i]
        if x[i]<minn:
            minn=x[i]
    print("maximum number is {} & minimum number is {}".format(maxx,minn))
d=[8,2,6,3,8,900,1,24,2,13,23]
maxmin(d)
            


# ### Write a Python function that takes two lists and returns True if they have at least one common member.

# In[69]:


def common_member (x,y):
    
    for i in range(0,len(x)):
        if x[i]in y :
            return True
        
       
a=[1,2,4,1,6,2,6]
s=[8,5,3,1,8,5,2]
common_member(a,s)


# ### Write a Python function to calculate the factorial of a number (a non-negative integer). The function accepts the number from the user

# In[33]:


def factorial(x):
    
    if x==1:
        return 1
    else:
        return x*factorial(x-1)
c=int(input("enter a number"))
factorial(c)


# ### Write a Python function to check whether a number is in a given range.
# 
# ### The range is from 3 to 11
# 

# In[38]:


n=int(input('enter anumber'))
def inrange(x):
    if x in range(3,12):
        print('in range')
    else:
        print("out of range")
inrange(n)


# ### Write a  program to create the multiplication table (from 1 to 10) of a number.

# In[39]:


v=int(input('enter a number'))
def table(b):
    for i in range(1,11):
        print("{}*{}={}".format(b,i,b*i))
table(v)


# #### LESSER OF TWO EVENS: Write a function that returns the lesser of two given numbers *if* both numbers are even, but returns the greater if one or both numbers are odd
#     lesser_of_two_evens(2,4) --> 2
#     lesser_of_two_evens(2,5) --> 5

# In[45]:


x=int(input("enter two numbers"))
y=int(input())
if x%2==0 and y%2==0:
    if x<y:
        less=x
        print("lesser of two evens({},{})--> {}".format(x,y,less))
    else:
        less=y
        print("lesser of two evens({},{})--> {}".format(x,y,less))
else:
    if x>y:
        greater=x
        print("grater of two numbers ({},{})-->{}".format(x,y,greater))
    else:
        greater=y
        print("grater of two numbers ({},{})-->{}".format(x,y,greater))


# #### ANIMAL CRACKERS: Write a function takes a two-word string and returns True if both words begin with same letter
#     animal_crackers('Levelheaded Llama') --> True
#     animal_crackers('Crazy Kangaroo') --> False

# In[51]:


x=input("enter 1st word:")
y=input("ebter 2nd word:")
def asd(s,d):
    if s[0]==d[0]:
        return True
    else:
        return False
asd(x,y)


# #### MAKES TWENTY: Given two integers, return True if the sum of the integers is 20 *or* if one of the integers is 20. If not, return False
# 
#     makes_twenty(20,10) --> True
#     makes_twenty(12,8) --> True
#     makes_twenty(2,3) --> False

# In[55]:


q=int(input("enter 1st number"))
w=int(input("enter 2nd number"))
if q==20 or w==20 or (q+w==20):
    print( True)
else:
    print( False)


# #### ALMOST THERE: Given an integer n, return True if n is within 10 of either 100 or 200
# 
#     almost_there(90) --> True
#     almost_there(104) --> True
#     almost_there(150) --> False
#     almost_there(209) --> True
#     
# NOTE: `abs(num)` returns the absolute value of a number

# In[67]:


x=int(input("enter a number"))
if( x in range(90,111))or(x in range(190,211)):
    print("true")
else:
    print("false")
    


# #### BLACKJACK: Given three integers between 1 and 11, if their sum is less than or equal to 21, return their sum. If their sum exceeds 21 *and* there's an eleven, reduce the total sum by 10. Finally, if the sum  exceeds 21, return 'BUST'
#     blackjack(5,6,7) --> 18
#     blackjack(9,9,9) --> 'BUST'
#     blackjack(9,9,11) --> 19

# In[61]:


x=int(input('1st number: '))
y=int(input('2nd number: '))
z=int(input('3rd number: '))
if (x+y+z<22):
    print(x+y+z)
elif(x+y+z>21)and (x==11 or y==11 or z==11):
    print(x+y+z-10)
else:
    print("bust")


# In[ ]:




