#!/usr/bin/env python
# coding: utf-8

# In[1]:


class calculator():
    def __init__ (self,num1,num2,operation):
        self.num1=num1
        self.num2=num2
        self.operation=operation
    def add(self):
        print(self.num1+self.num2)
    def sub(self):
        print(self.num1-self.num2)
    def mul(self):
        print(self.num1*self.num2)
    def div(self):
        print(self.num1/self.num2)
    def calculate(self):
        if operation=='+':
            self.add()
        elif operation=='-':
            self.sub()
        elif operation=='*':
            self.mul()
        elif operation=='/':
            self.div()
            

Num1=int(input('enter first number'))
Num2=int(input('enter secound number'))
operation=input('choose your operation + , - , * , / ')
s=calculator(Num1,Num2,'+')
s.calculate()
        


# In[ ]:




